# Generated by Django 4.2 on 2024-09-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["-created"],
                "verbose_name": "Imagen",
                "verbose_name_plural": "Imagenes",
            },
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descipción"),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Titulo"),
        ),
    ]
